; USER INPUT CODE AND PRINT THE USER INPUT
ORG 0100h

.DATA
X DB ?
Y DB ?
Z DB ? 

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    MOV AH, 1    ; USER INPUT      
    INT 21H      ; STORE USER INPUT INTO AL REGISTER 
    SUB AL, 48
    MOV X, AL    ; MOV AL VALUE TO BL 
    
    MOV AH, 1
    INT 21H      ; STORE USER INPUT INTO AL REGISTER 
    SUB AL, 48
    MOV Y, AL
    
    MOV BL, X      ; SUMMATION 
    ADD BL, Y
    MOV Z, BL
    
    MOV AH, 2       ; NEW LINE CODE
    MOV DL, 0DH
    INT 21h
    MOV DL, 0AH
    INT 21h    
    
    MOV DL, Z       ;MOV FROM SUM TO DL REGISTER
    ADD DL, 48

    MOV AH, 2         ; USER OUTPUT
    INT 21H
    
    MOV AH,4CH        ; RETURN TO DOS
    INT 21H
    
    MAIN ENDP
END MAIN
RET